### PR TITLE
fix: clean up organization of errors to separate file

### LINKED ISSUE #36: Add support for error objects
In order to use custom error objects instead of relying on their actual name strings we can create an `errors/` directory with the errors on it. Internally in the program we can simply consumer that just like any other import and for external access projects can just require it as well like:

```js
const { CustomError } = require('express-version-route/errors/')
```
where `errors/` folder will have an index.js that will export all error classes

cc @captaincaius

### PR DESCRIPTION
**Pull request by trycatchal**
fixes: #36

### CODE REVIEW

File: errors/index.js [hunk 1]
```diff
@@ -0,0 +1,11 @@
+
```
Comment (lirantal) [inline errors/index.js]:
```suggestion
'use strict'
```

**Review by lirantal — APPROVED** [review]
Super!
